### ISSUE TITLE
Sophisticated Storage/Backpacks Support

### ISSUE THREAD

**Issue by Poke5555** [DAQEM/GriefLogger#27]
Currently the inspect command(ive not tested lookup) doesnt show items removed/added from inventories from these mods,
Is there a way for admins to add missing storages from mods or is that something that only you can do?
https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

**Comment by DAQEM** [comment]
This is not something admins will be able to do. And to implement this feature into the mod is a bit excessive because not that many people would use this feature but it will still fill up the database. Maybe it could be an addon (separate mod) or something you can enable in the config. But I don't have the time to built this at the moment.
